### ISSUE TITLE
Still on? :)

### ISSUE THREAD

**Issue by ChristianWeyer** [trnelson/nstore#1]
Hey - are you still planning to evolve this neat little project?
Thank you.

**Comment by trnelson** [comment]
Hi Christian,

Thanks for your comment! I definitely will working on NStore. I've been itching to, honestly. I have been a bit busy the past few weeks with some work and personal stuff, but there's a light at the end of the tunnel and as soon as I get unburied, I'll jump right back in!

**Comment by ChristianWeyer** [comment]
Cool! Thanks.
